import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-global',
  templateUrl: './global.component.html',
  styleUrls: ['./global.component.css']
})
export class GlobalComponent implements OnInit {

  public static localhost: string = 'http://127.0.0.1:8000';
  public static website: string = 'https://clenicback.clenic.id';
  public static url: string = GlobalComponent.localhost;

  public static employee: any = 
  [
    { username: "Wirahman", firstName: "Wirahman", lastName: "Usman", email: "Wira_uk@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: { id:"1", groupName: "Group 1" }, description: "Description" },
    { username: "Wimbisono", firstName: "Wimbisono", lastName: "Usman", email: "Wimbisono@yahoo.com", birthDate: "1993-07-31", basicSalary: "5000000", status: "Active", group: { id:"1", groupName: "Group 1" }, description: "Description" },
    { username: "Username 1", firstName: "Nama Depan 1", lastName: "Nama Belakang 1", email: "Email1@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: { id:"1", groupName: "Group 1" }, description: "Description" },
    { username: "Username 2", firstName: "Nama Depan 2", lastName: "Nama Belakang 2", email: "Email2@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: { id:"1", groupName: "Group 1" }, description: "Description" },
    { username: "Username 3", firstName: "Nama Depan 3", lastName: "Nama Belakang 3", email: "Email3@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: { id:"1", groupName: "Group 1" }, description: "Description" },
    { username: "Username 4", firstName: "Nama Depan 4", lastName: "Nama Belakang 4", email: "Email4@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: { id:"1", groupName: "Group 1" }, description: "Description" },
    { username: "Username 5", firstName: "Nama Depan 5", lastName: "Nama Belakang 5", email: "Email5@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: { id:"1", groupName: "Group 1" }, description: "Description" },
    { username: "Username 6", firstName: "Nama Depan 6", lastName: "Nama Belakang 6", email: "Email6@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: { id:"1", groupName: "Group 1" }, description: "Description" },
    { username: "Username 7", firstName: "Nama Depan 7", lastName: "Nama Belakang 7", email: "Email7@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: { id:"1", groupName: "Group 1" }, description: "Description" },
    { username: "Username 8", firstName: "Nama Depan 8", lastName: "Nama Belakang 8", email: "Email8@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: { id:"1", groupName: "Group 1" }, description: "Description" },
    { username: "Username 9", firstName: "Nama Depan 9", lastName: "Nama Belakang 9", email: "Email9@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: { id:"1", groupName: "Group 1" }, description: "Description" },
    { username: "Username 10", firstName: "Nama Depan 10", lastName: "Nama Belakang 10", email: "Email10@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: { id:"1", groupName: "Group 1" }, description: "Description" },
    { username: "Username 11", firstName: "Nama Depan 11", lastName: "Nama Belakang 11", email: "Email11@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: { id:"1", groupName: "Group 1" }, description: "Description" },
    { username: "Username 12", firstName: "Nama Depan 12", lastName: "Nama Belakang 12", email: "Email12@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: { id:"1", groupName: "Group 1" }, description: "Description" },
    { username: "Username 13", firstName: "Nama Depan 13", lastName: "Nama Belakang 13", email: "Email13@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: { id:"1", groupName: "Group 1" }, description: "Description" },
    { username: "Username 14", firstName: "Nama Depan 14", lastName: "Nama Belakang 14", email: "Email14@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: { id:"1", groupName: "Group 1" }, description: "Description" },
    { username: "Username 15", firstName: "Nama Depan 15", lastName: "Nama Belakang 15", email: "Email15@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: { id:"1", groupName: "Group 1" }, description: "Description" },
    { username: "Username 16", firstName: "Nama Depan 16", lastName: "Nama Belakang 16", email: "Email16@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: { id:"1", groupName: "Group 1" }, description: "Description" },
    { username: "Username 17", firstName: "Nama Depan 17", lastName: "Nama Belakang 17", email: "Email17@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: { id:"1", groupName: "Group 1" }, description: "Description" },
    { username: "Username 18", firstName: "Nama Depan 18", lastName: "Nama Belakang 18", email: "Email18@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: { id:"1", groupName: "Group 1" }, description: "Description" },
    { username: "Username 19", firstName: "Nama Depan 19", lastName: "Nama Belakang 19", email: "Email19@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: { id:"1", groupName: "Group 1" }, description: "Description" },
    { username: "Username 20", firstName: "Nama Depan 20", lastName: "Nama Belakang 20", email: "Email20@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: "Group 2", description: "Description" },
    { username: "Username 21", firstName: "Nama Depan 21", lastName: "Nama Belakang 21", email: "Email21@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: "Group 2", description: "Description" },
    { username: "Username 22", firstName: "Nama Depan 22", lastName: "Nama Belakang 22", email: "Email22@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: "Group 2", description: "Description" },
    { username: "Username 23", firstName: "Nama Depan 23", lastName: "Nama Belakang 23", email: "Email23@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: "Group 2", description: "Description" },
    { username: "Username 24", firstName: "Nama Depan 24", lastName: "Nama Belakang 24", email: "Email24@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: "Group 2", description: "Description" },
    { username: "Username 25", firstName: "Nama Depan 25", lastName: "Nama Belakang 25", email: "Email25@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: "Group 2", description: "Description" },
    { username: "Username 26", firstName: "Nama Depan 26", lastName: "Nama Belakang 26", email: "Email26@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: "Group 2", description: "Description" },
    { username: "Username 27", firstName: "Nama Depan 27", lastName: "Nama Belakang 27", email: "Email27@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: "Group 2", description: "Description" },
    { username: "Username 28", firstName: "Nama Depan 28", lastName: "Nama Belakang 28", email: "Email28@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: "Group 2", description: "Description" },
    {  username: "Username 29", firstName: "Nama Depan29", lastName: "Nama Belakang 29", email: "Email29@yahoo.com", birthDate: "1989-09-02", basicSalary: "5000000", status: "Active", group: "Group 2", description: "Description" },
    {  username: "Username 30", firstName: "Nama Depan30", lastName: "Nama Belakang 30", email: "Email30@yahoo.com", birthDate: "1989-09-03", basicSalary: "5000000", status: "Active", group: "Group 3", description: "Description" },
    {  username: "Username 31", firstName: "Nama Depan31", lastName: "Nama Belakang 31", email: "Email31@yahoo.com", birthDate: "1989-09-03", basicSalary: "5000000", status: "Active", group: "Group 3", description: "Description" },
    {  username: "Username 32", firstName: "Nama Depan32", lastName: "Nama Belakang 32", email: "Email32@yahoo.com", birthDate: "1989-09-03", basicSalary: "5000000", status: "Active", group: "Group 3", description: "Description" },
    {  username: "Username 33", firstName: "Nama Depan33", lastName: "Nama Belakang 33", email: "Email33@yahoo.com", birthDate: "1989-09-03", basicSalary: "5000000", status: "Active", group: "Group 3", description: "Description" },
    {  username: "Username 34", firstName: "Nama Depan34", lastName: "Nama Belakang 34", email: "Email34@yahoo.com", birthDate: "1989-09-03", basicSalary: "5000000", status: "Active", group: "Group 3", description: "Description" },
    {  username: "Username 35", firstName: "Nama Depan35", lastName: "Nama Belakang 35", email: "Email35@yahoo.com", birthDate: "1989-09-03", basicSalary: "5000000", status: "Active", group: "Group 3", description: "Description" },
    {  username: "Username 36", firstName: "Nama Depan36", lastName: "Nama Belakang 36", email: "Email36@yahoo.com", birthDate: "1989-09-03", basicSalary: "5000000", status: "Active", group: "Group 3", description: "Description" },
    {  username: "Username 37", firstName: "Nama Depan37", lastName: "Nama Belakang 37", email: "Email37@yahoo.com", birthDate: "1989-09-03", basicSalary: "5000000", status: "Active", group: "Group 3", description: "Description" },
    {  username: "Username 38", firstName: "Nama Depan38", lastName: "Nama Belakang 38", email: "Email38@yahoo.com", birthDate: "1989-09-03", basicSalary: "5000000", status: "Active", group: "Group 3", description: "Description" },
    {  username: "Username 39", firstName: "Nama Depan39", lastName: "Nama Belakang 39", email: "Email39@yahoo.com", birthDate: "1989-09-03", basicSalary: "5000000", status: "Active", group: "Group 3", description: "Description" },
    {  username: "Username 40", firstName: "Nama Depan40", lastName: "Nama Belakang 40", email: "Email40@yahoo.com", birthDate: "1989-09-04", basicSalary: "5000000", status: "Active", group: "Group 4", description: "Description" },
    {  username: "Username 41", firstName: "Nama Depan41", lastName: "Nama Belakang 41", email: "Email41@yahoo.com", birthDate: "1989-09-04", basicSalary: "5000000", status: "Active", group: "Group 4", description: "Description" },
    {  username: "Username 42", firstName: "Nama Depan42", lastName: "Nama Belakang 42", email: "Email42@yahoo.com", birthDate: "1989-09-04", basicSalary: "5000000", status: "Active", group: "Group 4", description: "Description" },
    {  username: "Username 43", firstName: "Nama Depan43", lastName: "Nama Belakang 43", email: "Email43@yahoo.com", birthDate: "1989-09-04", basicSalary: "5000000", status: "Active", group: "Group 4", description: "Description" },
    {  username: "Username 44", firstName: "Nama Depan44", lastName: "Nama Belakang 44", email: "Email44@yahoo.com", birthDate: "1989-09-04", basicSalary: "5000000", status: "Active", group: "Group 4", description: "Description" },
    {  username: "Username 45", firstName: "Nama Depan45", lastName: "Nama Belakang 45", email: "Email45@yahoo.com", birthDate: "1989-09-04", basicSalary: "5000000", status: "Active", group: "Group 4", description: "Description" },
    {  username: "Username 46", firstName: "Nama Depan46", lastName: "Nama Belakang 46", email: "Email46@yahoo.com", birthDate: "1989-09-04", basicSalary: "5000000", status: "Active", group: "Group 4", description: "Description" },
    {  username: "Username 47", firstName: "Nama Depan47", lastName: "Nama Belakang 47", email: "Email47@yahoo.com", birthDate: "1989-09-04", basicSalary: "5000000", status: "Active", group: "Group 4", description: "Description" },
    {  username: "Username 48", firstName: "Nama Depan48", lastName: "Nama Belakang 48", email: "Email48@yahoo.com", birthDate: "1989-09-04", basicSalary: "5000000", status: "Active", group: "Group 4", description: "Description" },
    {  username: "Username 49", firstName: "Nama Depan49", lastName: "Nama Belakang 49", email: "Email49@yahoo.com", birthDate: "1989-09-04", basicSalary: "5000000", status: "Active", group: "Group 4", description: "Description" },
    {  username: "Username 50", firstName: "Nama Depan50", lastName: "Nama Belakang 50", email: "Email50@yahoo.com", birthDate: "1989-09-05", basicSalary: "5000000", status: "Active", group: "Group 5", description: "Description" },
    {  username: "Username 51", firstName: "Nama Depan51", lastName: "Nama Belakang 51", email: "Email51@yahoo.com", birthDate: "1989-09-05", basicSalary: "5000000", status: "Active", group: "Group 5", description: "Description" },
    {  username: "Username 52", firstName: "Nama Depan52", lastName: "Nama Belakang 52", email: "Email52@yahoo.com", birthDate: "1989-09-05", basicSalary: "5000000", status: "Active", group: "Group 5", description: "Description" },
    {  username: "Username 53", firstName: "Nama Depan53", lastName: "Nama Belakang 53", email: "Email53@yahoo.com", birthDate: "1989-09-05", basicSalary: "5000000", status: "Active", group: "Group 5", description: "Description" },
    {  username: "Username 54", firstName: "Nama Depan54", lastName: "Nama Belakang 54", email: "Email54@yahoo.com", birthDate: "1989-09-05", basicSalary: "5000000", status: "Active", group: "Group 5", description: "Description" },
    {  username: "Username 55", firstName: "Nama Depan55", lastName: "Nama Belakang 55", email: "Email55@yahoo.com", birthDate: "1989-09-05", basicSalary: "5000000", status: "Active", group: "Group 5", description: "Description" },
    {  username: "Username 56", firstName: "Nama Depan56", lastName: "Nama Belakang 56", email: "Email56@yahoo.com", birthDate: "1989-09-05", basicSalary: "5000000", status: "Active", group: "Group 5", description: "Description" },
    {  username: "Username 57", firstName: "Nama Depan57", lastName: "Nama Belakang 57", email: "Email57@yahoo.com", birthDate: "1989-09-05", basicSalary: "5000000", status: "Active", group: "Group 5", description: "Description" },
    {  username: "Username 58", firstName: "Nama Depan58", lastName: "Nama Belakang 58", email: "Email58@yahoo.com", birthDate: "1989-09-05", basicSalary: "5000000", status: "Active", group: "Group 5", description: "Description" },
    {  username: "Username 59", firstName: "Nama Depan59", lastName: "Nama Belakang 59", email: "Email59@yahoo.com", birthDate: "1989-09-05", basicSalary: "5000000", status: "Active", group: "Group 5", description: "Description" },
    {  username: "Username 60", firstName: "Nama Depan60", lastName: "Nama Belakang 60", email: "Email60@yahoo.com", birthDate: "1989-09-06", basicSalary: "6000000", status: "Active", group: "Group 6", description: "Description" },
    {  username: "Username 61", firstName: "Nama Depan61", lastName: "Nama Belakang 61", email: "Email61@yahoo.com", birthDate: "1989-09-06", basicSalary: "6000000", status: "Active", group: "Group 6", description: "Description" },
    {  username: "Username 62", firstName: "Nama Depan62", lastName: "Nama Belakang 62", email: "Email62@yahoo.com", birthDate: "1989-09-06", basicSalary: "6000000", status: "Active", group: "Group 6", description: "Description" },
    {  username: "Username 63", firstName: "Nama Depan63", lastName: "Nama Belakang 63", email: "Email63@yahoo.com", birthDate: "1989-09-06", basicSalary: "6000000", status: "Active", group: "Group 6", description: "Description" },
    {  username: "Username 64", firstName: "Nama Depan64", lastName: "Nama Belakang 64", email: "Email64@yahoo.com", birthDate: "1989-09-06", basicSalary: "6000000", status: "Active", group: "Group 6", description: "Description" },
    {  username: "Username 65", firstName: "Nama Depan65", lastName: "Nama Belakang 65", email: "Email65@yahoo.com", birthDate: "1989-09-06", basicSalary: "6000000", status: "Active", group: "Group 6", description: "Description" },
    {  username: "Username 66", firstName: "Nama Depan66", lastName: "Nama Belakang 66", email: "Email66@yahoo.com", birthDate: "1989-09-06", basicSalary: "6000000", status: "Active", group: "Group 6", description: "Description" },
    {  username: "Username 67", firstName: "Nama Depan67", lastName: "Nama Belakang 67", email: "Email67@yahoo.com", birthDate: "1989-09-06", basicSalary: "6000000", status: "Active", group: "Group 6", description: "Description" },
    {  username: "Username 68", firstName: "Nama Depan68", lastName: "Nama Belakang 68", email: "Email68@yahoo.com", birthDate: "1989-09-06", basicSalary: "6000000", status: "Active", group: "Group 6", description: "Description" },
    {  username: "Username 69", firstName: "Nama Depan69", lastName: "Nama Belakang 69", email: "Email69@yahoo.com", birthDate: "1989-09-06", basicSalary: "6000000", status: "Active", group: "Group 6", description: "Description" },
    {  username: "Username 70", firstName: "Nama Depan70", lastName: "Nama Belakang 70", email: "Email70@yahoo.com", birthDate: "1989-09-07", basicSalary: "7000000", status: "Active", group: "Group 7", description: "Description" },
    {  username: "Username 71", firstName: "Nama Depan71", lastName: "Nama Belakang 71", email: "Email71@yahoo.com", birthDate: "1989-09-07", basicSalary: "7000000", status: "Active", group: "Group 7", description: "Description" },
    {  username: "Username 72", firstName: "Nama Depan72", lastName: "Nama Belakang 72", email: "Email72@yahoo.com", birthDate: "1989-09-07", basicSalary: "7000000", status: "Active", group: "Group 7", description: "Description" },
    {  username: "Username 73", firstName: "Nama Depan73", lastName: "Nama Belakang 73", email: "Email73@yahoo.com", birthDate: "1989-09-07", basicSalary: "7000000", status: "Active", group: "Group 7", description: "Description" },
    {  username: "Username 74", firstName: "Nama Depan74", lastName: "Nama Belakang 74", email: "Email74@yahoo.com", birthDate: "1989-09-07", basicSalary: "7000000", status: "Active", group: "Group 7", description: "Description" },
    {  username: "Username 75", firstName: "Nama Depan75", lastName: "Nama Belakang 75", email: "Email75@yahoo.com", birthDate: "1989-09-07", basicSalary: "7000000", status: "Active", group: "Group 7", description: "Description" },
    {  username: "Username 76", firstName: "Nama Depan76", lastName: "Nama Belakang 76", email: "Email76@yahoo.com", birthDate: "1989-09-07", basicSalary: "7000000", status: "Active", group: "Group 7", description: "Description" },
    {  username: "Username 77", firstName: "Nama Depan77", lastName: "Nama Belakang 77", email: "Email77@yahoo.com", birthDate: "1989-09-07", basicSalary: "7000000", status: "Active", group: "Group 7", description: "Description" },
    {  username: "Username 78", firstName: "Nama Depan78", lastName: "Nama Belakang 78", email: "Email78@yahoo.com", birthDate: "1989-09-07", basicSalary: "7000000", status: "Active", group: "Group 7", description: "Description" },
    {  username: "Username 79", firstName: "Nama Depan79", lastName: "Nama Belakang 79", email: "Email79@yahoo.com", birthDate: "1989-09-07", basicSalary: "7000000", status: "Active", group: "Group 7", description: "Description" },
    {  username: "Username 80", firstName: "Nama Depan80", lastName: "Nama Belakang 80", email: "Email80@yahoo.com", birthDate: "1989-09-08", basicSalary: "8000000", status: "Active", group: "Group 8", description: "Description" },
    {  username: "Username 81", firstName: "Nama Depan81", lastName: "Nama Belakang 81", email: "Email81@yahoo.com", birthDate: "1989-09-08", basicSalary: "8000000", status: "Active", group: "Group 8", description: "Description" },
    {  username: "Username 82", firstName: "Nama Depan82", lastName: "Nama Belakang 82", email: "Email82@yahoo.com", birthDate: "1989-09-08", basicSalary: "8000000", status: "Active", group: "Group 8", description: "Description" },
    {  username: "Username 83", firstName: "Nama Depan83", lastName: "Nama Belakang 83", email: "Email83@yahoo.com", birthDate: "1989-09-08", basicSalary: "8000000", status: "Active", group: "Group 8", description: "Description" },
    {  username: "Username 84", firstName: "Nama Depan84", lastName: "Nama Belakang 84", email: "Email84@yahoo.com", birthDate: "1989-09-08", basicSalary: "8000000", status: "Active", group: "Group 8", description: "Description" },
    {  username: "Username 85", firstName: "Nama Depan85", lastName: "Nama Belakang 85", email: "Email85@yahoo.com", birthDate: "1989-09-08", basicSalary: "8000000", status: "Active", group: "Group 8", description: "Description" },
    {  username: "Username 86", firstName: "Nama Depan86", lastName: "Nama Belakang 86", email: "Email86@yahoo.com", birthDate: "1989-09-08", basicSalary: "8000000", status: "Active", group: "Group 8", description: "Description" },
    {  username: "Username 87", firstName: "Nama Depan87", lastName: "Nama Belakang 87", email: "Email87@yahoo.com", birthDate: "1989-09-08", basicSalary: "8000000", status: "Active", group: "Group 8", description: "Description" },
    {  username: "Username 88", firstName: "Nama Depan88", lastName: "Nama Belakang 88", email: "Email88@yahoo.com", birthDate: "1989-09-08", basicSalary: "8000000", status: "Active", group: "Group 8", description: "Description" },
    {  username: "Username 89", firstName: "Nama Depan89", lastName: "Nama Belakang 89", email: "Email89@yahoo.com", birthDate: "1989-09-08", basicSalary: "8000000", status: "Active", group: "Group 8", description: "Description" },
    {  username: "Username 90", firstName: "Nama Depan90", lastName: "Nama Belakang 90", email: "Email90@yahoo.com", birthDate: "1999-09-09", basicSalary: "9000000", status: "Active", group: "Group 9", description: "Description" },
    {  username: "Username 91", firstName: "Nama Depan91", lastName: "Nama Belakang 91", email: "Email91@yahoo.com", birthDate: "1999-09-09", basicSalary: "9000000", status: "Active", group: "Group 9", description: "Description" },
    {  username: "Username 92", firstName: "Nama Depan92", lastName: "Nama Belakang 92", email: "Email92@yahoo.com", birthDate: "1999-09-09", basicSalary: "9000000", status: "Active", group: "Group 9", description: "Description" },
    {  username: "Username 93", firstName: "Nama Depan93", lastName: "Nama Belakang 93", email: "Email93@yahoo.com", birthDate: "1999-09-09", basicSalary: "9000000", status: "Active", group: "Group 9", description: "Description" },
    {  username: "Username 94", firstName: "Nama Depan94", lastName: "Nama Belakang 94", email: "Email94@yahoo.com", birthDate: "1999-09-09", basicSalary: "9000000", status: "Active", group: "Group 9", description: "Description" },
    {  username: "Username 95", firstName: "Nama Depan95", lastName: "Nama Belakang 95", email: "Email95@yahoo.com", birthDate: "1999-09-09", basicSalary: "9000000", status: "Active", group: "Group 9", description: "Description" },
    {  username: "Username 96", firstName: "Nama Depan96", lastName: "Nama Belakang 96", email: "Email96@yahoo.com", birthDate: "1999-09-09", basicSalary: "9000000", status: "Active", group: "Group 9", description: "Description" },
    {  username: "Username 97", firstName: "Nama Depan97", lastName: "Nama Belakang 97", email: "Email97@yahoo.com", birthDate: "1999-09-09", basicSalary: "9000000", status: "Active", group: "Group 9", description: "Description" },
    {  username: "Username 98", firstName: "Nama Depan98", lastName: "Nama Belakang 98", email: "Email98@yahoo.com", birthDate: "1999-09-09", basicSalary: "9000000", status: "Active", group: "Group 9", description: "Description" },
    {  username: "Username 99", firstName: "Nama Depan99", lastName: "Nama Belakang 99", email: "Email99@yahoo.com", birthDate: "1999-09-09", basicSalary: "9000000", status: "Active", group: "Group 9", description: "Description" },
    
  ]

  public static groupEmployee: any = 
  [
    { id:"1", groupName: "Group 1" },
    { id:"2", groupName: "Group 2" },
    { id:"3", groupName: "Group 3" },
    { id:"4", groupName: "Group 4" },
    { id:"5", groupName: "Group 5" },
    { id:"6", groupName: "Group 6" },
    { id:"7", groupName: "Group 7" },
    { id:"8", groupName: "Group 8" },
    { id:"9", groupName: "Group 9" },
    { id:"10", groupName: "Group 10" },
    { id:"11", groupName: "Group 11" },
    { id:"12", groupName: "Group 12" },
    { id:"13", groupName: "Group 13" },
    { id:"14", groupName: "Group 14" },
    { id:"15", groupName: "Group 15" },
    { id:"16", groupName: "Group 16" },
    { id:"17", groupName: "Group 17" },
    { id:"18", groupName: "Group 18" },
    { id:"19", groupName: "Group 19" },
    { id:"20", groupName: "Group 20" },
  ]

  constructor() { }

  ngOnInit(): void {

  }

}
